### ISSUE TITLE
Week 4: Error Handling Sir this is a Wendys

### ISSUE THREAD

**Issue by ganning127** [ganning127/asdfasdf#16]
Week 4 Step 2 ⬤⬤◯◯◯◯◯ | 🕐 Estimated completion: 20-25 minutes

#### Demo: [🐰](https://week4step2.emilychen10.repl.co)
*Ideally, users will fill the web form with the correct information. However, people make mistakes. In this step, we will be implementing some form validation to make sure that a user has inputted text value before submitting their password.*

<p align="center">
   <img src="https://user-images.githubusercontent.com/69332964/121591591-ad89c080-ca07-11eb-9174-4b597ad4134f.png" width="500" height="250" />
</p>

### ✅  Task:
- [ ] Check you are on the `bunnimage-frontend` branch 
- [ ] Change your HTML form to accept `multipart/form-data` in `index.html`
- [ ] Add a file input to `index.html` that accepts `image/x-png,image/jpeg` and add the attribute `name=image`
- [ ] Modify the function in `index.js` to create an alert if either the file input or the `name` input is null
- [ ] Modify the button so that it submits the form by changing its `type` attribute to `"submit"`
- [ ] Prevent the page from reloading after submission
- [ ] Commit your updated code to `bunnimage/index.html` and `bunnimage/script.js`

### 🚧 Test your Work
Open up your LiveServer plugin and start your server.

<details>
<summary>:pencil: You have three test cases to try</summary>
  </br>

1. **The "correct" way**: Submit both a file and text. Check that you receive "Thanks!"
2. **The "unexpected" way (file)**: Submit a file that is not png or jpeg. Does it work?
3. **The "unexpected" way (text input)**: Try submitting without entering a username. You should get an alert box that says "No name error."
  <br><br/>
</details>

## Accepting Images as an Input
In HTML Forms, the `enctype` attribute specifies how the form-data should be encoded when submitting it to the server. Like we learned before, if we want to upload files, we need send form-data encoded as `multipart/form-data`

```html
    <h1>Bunnimage</h1>
    <form enctype="multipart/form-data">
    <label>Code: </label>
```

To add the image upload input, add an additional file input within the form & change the submit button's `type`.

```html 
<form enctype="multipart/form-data">
   <input type="file" name="image"></input>
   <input id="username" type="text" placeholder="Enter your file's name">
   <input type="submit" />
```

## Input Validation?
We need to validate two things. 

<details>
<summary> :one: The image is either in the .png or .jpeg format</summary>
  </br>

The HTML `<input>` accept Attribute specifies a filter for what file types the user can pick from the file input dialog box. The accept attribute can only be used with <input type="file">.

```html 
<form enctype="multipart/form-data">
    <input type="file" accept="image/x-png,image/jpeg" name="image"></input>
    <input id="username" type="text" placeholder="Enter your file's name">
    <input type="submit" />
```

Additionally, the HTML may not catch an invalid file 100% of the time, so we will also need to use JavaScript to do some validation. 

1. Once a file is uploaded, you will need to display an error when a file of invalid format is added.
2. Get the [name of the file](https://stackoverflow.com/questions/857618/javascript-how-to-extract-filename-from-a-file-input-control) from the input box (use the `change` event listener for the input)
3. Check if the file is either `.png` or `.jpeg` using [this StackOverflow post](https://stackoverflow.com/questions/8231058/file-type-validation-with-javascript)

  <br><br/>
</details>

<details>
<summary> :two: The text box isn't empty</summary>
  </br>

To validate that the name isn't null, check if `document.getElementById("username").value` isn't empty, to change the `output` div to "Thanks!", or display an `alert("No name error.")`

> :bulb: **Hint**: Use your JavaScript conditional skills!
  <br><br/>
</details>

**Comment by ganning127** [comment]
closed via oauth
